# Generated by Django 5.2.5 on 2025-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customer_name_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
