# Generated by Django 5.2.5 on 2025-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer_slug_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_sale_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
