# Generated by Django 5.2.5 on 2025-08-17 21:51

from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')


    add_product = Permission.objects.get(codename='add_product')
    change_product = Permission.objects.get(codename='change_product')
    delete_product = Permission.objects.get(codename='delete_product')
    view_product = Permission.objects.get(codename='view_product')

    view_revenue = Permission.objects.get(codename='view_revenue')


    seller_group, created = Group.objects.get_or_create(name='Seller')
    seller_permissions = [
        add_product, change_product, delete_product, view_product,
    ]
    seller_group.permissions.set(seller_permissions)


    owner_group, created = Group.objects.get_or_create(name='Owner')
    dono_permissions = seller_permissions + [view_revenue]
    owner_group.permissions.set(dono_permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]
